export const ADD_POST = "ADD_POST"
export const SET_POST_VALUE = "SET_POST_VALUE"
export const ADD_MESSAGE = "ADD_MESSAGE"
export const SET_MESSAGE_VALUE = "SET_MESSAGE_VALUE"
export const LOAD_USERS = "LOAD_USERS"
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE"

